version: '3.9'
services:
  api:
    container_name: source-base-backend
    build: 
      context: .
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - database
      - cache
    links:
      - database
      - cache
  cache:
    container_name: source-base-redis
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6380:6379'
    volumes: 
      - cache:/data
  database:
    container_name: source-base-database
    image: postgres:14-alpine
    restart: always
    ports:
      - 5434:5432
    volumes: 
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=base-go
volumes:
  db:
    driver: local
  cache:
    driver: local