CREATE TABLE "role" (
    "id" int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" varchar,
    "code" varchar,
    "description" varchar,
    "created_at" timestamp DEFAULT (now()),
    "updated_at" timestamp DEFAULT (now())
)

