CREATE TABLE "status" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "code" varchar,
    "name" varchar,
    "type" varchar,
    "description" varchar,

    "created_at" timestamp DEFAULT (now()),
    "updated_at" timestamp DEFAULT (now())
)