CREATE TABLE "user" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "username" varchar,
    "password" varchar,
    "status_id" int,
    "created_at" timestamp DEFAULT (now()),
    "updated_at" timestamp DEFAULT (now()),
    "deleted_at" timestamp
);

ALTER TABLE "user" ADD FOREIGN KEY ("status_id") REFERENCES "status" ("id");